### ISSUE TITLE
Minus time on results

### ISSUE THREAD

**Issue by couci** [MichaelKohler/remo-mean-time-approval#1]
Problem statement: In some bugs people set the remo-approval flag from + to ? and never changed it back to +
Result: On the script we get times of review with - in the beginning
Suggested solution: the script needs to take consideration only bugs that have a flag of remo-approval + or - so it can filter out those situations.

**Comment by MichaelKohler** [comment]
Best case scenario would be a check to make sure that we pick the correction ? -> +/- combination.

Example:
1. flag set to ?
2. flag set to +
3. flag set to ? again

--> we pick the 1. und 2. combination

**Comment by MichaelKohler** [comment]
Fixed in version 3.1
