### ISSUE TITLE
Over and under 500 budget requests

### ISSUE THREAD

**Issue by couci** [MichaelKohler/remo-mean-time-approval#2]
I would like to see what is the difference on the reviewing time between a single reviewer and the whole council/review team
The difference we could see is that:
- when it is under 500 Whiteboard should be: Council Reviewer Assigned / Review Team member Assigned
- when it is over 500 Whiteboard should be: Council approval needed/ Review Team approval needed **and** need-info flag: reps-council or review-team

The only problem I see is that we might loose some early bugs cause we established that rules around 3 years ago

**Comment by MichaelKohler** [comment]
In terms of output, I could imagine the following:

Add a new column "approvalBody" which contains either "single" (single council member), reps-council or review-team. Then to decide this we parse the whiteboard and if applicable the need-info flag.

This would enable you to:
- Filter for reps-council and then calculate the average of all remaining differences
- Filter for reps-review and then calculate the average of all remaining differences
- Filter for single and then calculate the average of all remaining differences

Does that sounds good?

**Comment by couci** [comment]
yes this is excellent thanks :)

**Comment by MichaelKohler** [comment]
This will be in version 3.1. I'll fix the other open bug and then send you the sheet as always.
