### ISSUE TITLE
Mentor review time

### ISSUE THREAD

**Issue by nukeador** [MichaelKohler/remo-mean-time-approval#3]
It would be important to also get the time between the remo-review flag is set and granted (or rejected), so we can identify bottlenecks in the process.

**Comment by MichaelKohler** [comment]
Thanks Nuke. @couci already has v2.0 of it as spreadsheet which includes this data. I'll keep this open to add a changelog. The version of the code with review? and review+ data is tagged here as v2.0 in git.

Glad to see that we can get out something from that data!

**Comment by nukeador** [comment]
Great, super excited about this, it's going to be key to take data-driven decisions in the near future :-)

**Comment by MichaelKohler** [comment]
Opened https://github.com/MichaelKohler/remo-mean-time-approval/issues/4 for the CHANGELOG file
